Mentoring-t-18 알고리즘 문제풀이 과제 제출
BI-kotlin-in-action/Juyeol-Song pull request #2
Opened 2023-10-08 17:11 UTC by Unagi-zoso

코틀린으로 알고리즘 문제풀이 과제 제출하겠습니다.

잘 부탁드리겠습니다!

2023-10-09 11:45 UTC, konempty requested changes
크 고생하셨습니다 👍 👍 
조금만 수정부탁드려요~!

2023-10-09 11:45 UTC, konempty commented on Boj10282.kt
> +    bw.close()
개취이긴한데 저는 요렇게 스트림처리에선 `try with resource`를 선호하구여
나중에 배울 내용이지만 코틀린에서는 스트림을 use라는 키워드를 통해 열고 닫는답니다~!
지금은 그대로 두셔도 좋구요 나중에 use키워드를 배우면 그때부턴 그걸 사용해주세요  ㅎㅎ

2023-10-09 11:45 UTC, konempty commented on Boj12886.kt
> +data class Pair(val x: Int, val y: Int)
앗 ㅋㅋㅋㅋ 코틀린은 페어가 기본으로 제공되는 자료구조예요!
참고로 Triple이라는 자료형도 있습니다 ㅋㅋㅋ

2023-10-09 11:45 UTC, konempty commented on Boj2533.kt
> +val dp = Array(MAX_NUM_OF_NODES) { IntArray(2) { 0 } }
IntArray는 기본적으로 크기만큼 0으로 초기화되기때문에 {0}은 불필요한 코드가 될것 같아요!

2023-10-09 11:45 UTC, konempty commented on Boj10282.kt
> +import java.lang.Integer.max
자바의 min/max 대신에 코틀린.math.min/max를 써주세요!

2023-10-09 11:45 UTC, konempty commented on Boj10282.kt
> +    // backing property는 이렇게 쓰는건가요? 살짝 억지로 쓴 느낌이..
네네 쓰는 방법은 맞는데 파일 한개정도 사이즈의 프로그램에서는 오버 엔지니어링에 될수도 있을것 같아요! ㅎㅎ 
그래도 써보신다는건 좋을것 같습니다~!

2023-10-09 11:45 UTC, konempty commented on Boj2533.kt
> +val visited = Array(MAX_NUM_OF_NODES) { false }
윗줄의. IntAaray처럼 BooleanArray는 어떨까요?

2023-10-09 11:45 UTC, konempty commented on Boj3108.kt
> +    constructor(list: List<String>) : this(list[0].toInt(), list[1].toInt(), list[2].toInt(), list[3].toInt())
오 ㅋㅋㅋㅋ 요 부생성자를 사용한 코드 너무 좋습니다~! 💯

2023-10-09 11:45 UTC, konempty commented on Boj3108.kt
> +    rectangles = Array(n) { br.readLine().split(" ").let { Rectangle(it) } }
split은 객체 생성 역할일것 같아보여서 문자열을 split하는 역할까지 부생성자의 역할이라면 어떨까요?
요건 개취라 적용안하셔도 좋습니다~!

2023-10-09 11:45 UTC, konempty commented on Boj12886.kt
> +    while (q.isNotEmpty()) { // 변수 재사용하기 싫어 의미없이 변수를 만드는 데 괜찮은건가 생각이 드네요.
오호... 주석으로 달아주신 질문이 이해가 안되는데
q라는 파라메터가 불필요하다는걸까요??

2023-10-09 11:45 UTC, konempty commented on Boj3108.kt
> +        (y1 == 0 && (x1 <= 0 && x2 >= 0)) || (y2 == 0 && (x1 <= 0 && x2 >= 0))
((x1 == 0 || x2 == 0) && (y1 <= 0 && y2 >= 0)) || 
((y1 == 0 || y2 == 0) && (x1 <= 0 && x2 >= 0))
요걸 의도하신거 맞을까요??

2023-10-09 11:45 UTC, konempty commented on Boj3108.kt
> +// 함수를 호출하는 부분에서(50번 줄) ! 연산자를 쓰고싶지 않아 isOverlap() -> isNotOverlap()으로 수정하였는데 클린코드 관점에서 괜찮은 방식일까요? 큰 영향이 있나 싶은 생각도 드네요.
으흠... 저는 큰 문제 없지않을까 싶네요 ㅋㅋㅋㅋ
그리고 알고리즘 문제 풀이에서는 클린코드를 지키는게 매우 어렵지 않을까 싶은데 
지키려고 노력하시는게 멋지네요!

2023-10-09 11:45 UTC, konempty commented on Boj6087.kt
> +import java.util.*
오호... 와일드카드 임포트는 쓰는걸 지양하시는게 좋아요..!
https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij
요 블로그 참고해서 설정 부탁드려요~!

2023-10-09 15:49 UTC, Unagi-zoso commented on Boj3108.kt
> +        (y1 == 0 && (x1 <= 0 && x2 >= 0)) || (y2 == 0 && (x1 <= 0 && x2 >= 0))
아하!
문제에서 조건으로  (−500 ≤ **x1 < x2** ≤ 500), (−500 ≤ **y1 < y2** ≤ 500) (x1, y1) 이렇게 두 점 사이에 관계가 있었네요. 지적해주신 부분이 맞습니다. 문제를 좀 더 주의 깊게 읽어보겠습니다! 
감사합니다!

2023-10-09 15:51 UTC, Unagi-zoso commented on Boj3108.kt
> +// 함수를 호출하는 부분에서(50번 줄) ! 연산자를 쓰고싶지 않아 isOverlap() -> isNotOverlap()으로 수정하였는데 클린코드 관점에서 괜찮은 방식일까요? 큰 영향이 있나 싶은 생각도 드네요.
아직 제대로 프로젝트를 진행해보지 못해서 이런 부분에서라도 의식해서 적용해보고 싶은 마음이 크네요! 감사합니다!

2023-10-09 15:52 UTC, Unagi-zoso commented on Boj6087.kt
> +import java.util.*
감사합니다!

2023-10-09 16:09 UTC, Unagi-zoso commented on Boj12886.kt
> +    while (q.isNotEmpty()) { // 변수 재사용하기 싫어 의미없이 변수를 만드는 데 괜찮은건가 생각이 드네요.
죄송합니다. 주석 내용이 구체적이지 못했네요.

정확하겐 l, r, other을 val로 선언하고 이후 for 문에서 조합을 리스트로 받아 i, j란 변수를 더 만들었습니다.
l, r, other, i, j 전부 의미도 명확하지 않고 가독성적인 부분에서도 변수가 많으니 헷갈릴 수 있을 것 같아 l, r을 var로 선언하고 l, r을 i, j가 하던 일에 재사용하면 메모리적으로 개선하고 변수의 수도 줄일 수 있어 어느 방향이 더 괜찮을지 생각했습니다.
다시 생각해보니 변수를 재사용하는게 오히려 코드를 추적하기에 더 안 좋을 듯 하다는 생각이 드네요.  알고리즘 문제풀이에서 변수명 하나하나에 너무 엄격한 건 약간 오버한건가 라는 생각도 드네요. 감사합니다!

```
while (q.isNotEmpty()) { // 변수 재사용하기 싫어 의미없이 변수를 만드는 것 같아 괜찮은건가 생각이 드네요.
        val (l, r) = q.poll()
        val other = sumOfAllStones - l - r

        if ((l == r) and (r == other)) return 1
        for ((i, j) in computePairCombinations(l, r, other)) {
            val newPair = when {
                i > j -> Pair(maxOf(i - j, j + j, sumOfAllStones - i - j), minOf(i - j, j + j, sumOfAllStones - i - j))
                i < j -> Pair(maxOf(i + i, j - i, sumOfAllStones - i - j), minOf(i + i, j - i, sumOfAllStones - i - j))
                else -> continue
            }
```

2023-10-09 16:59 UTC, Unagi-zoso commented on Boj12886.kt
> +data class Pair(val x: Int, val y: Int)
아하!! 감사합니다!!
이번 문제에선 Pair의 값을 접근할 때 first, second가 아닌 x, y로 표현하고 싶어 사용해보았습니다. (data class가 뭔지도궁금했네요!)
하지만 역시 라이브러리에서 제공해주는 걸 사용하는게 더 안정적이고 성능적으로도 신뢰할 수 있는 습관 같다는 생각이 드네요.
감사합니다!

2023-10-10 06:37 UTC, Unagi-zoso commented on Boj10282.kt
> +    bw.close()
감사합니다! use도 개인적으로 한 번 훑어봐야겠네요!

2023-10-10 06:38 UTC, Unagi-zoso commented on Boj2533.kt
> +val dp = Array(MAX_NUM_OF_NODES) { IntArray(2) { 0 } }
아하. 내장 콜렉션 관련 함수는 주석도 잘 적혀져 있으니 처음 쓰는 함수는 기본값을 확인하는 습관을 가져야겠네요! 감사합니다!

2023-10-10 06:39 UTC, Unagi-zoso commented on Boj2533.kt
> +val visited = Array(MAX_NUM_OF_NODES) { false }
그게 좋아보이네요! 감사합니다!

2023-10-10 06:40 UTC, Unagi-zoso commented on Boj3108.kt
> +    constructor(list: List<String>) : this(list[0].toInt(), list[1].toInt(), list[2].toInt(), list[3].toInt())
해해 감사합니다!

2023-10-10 06:46 UTC, Unagi-zoso commented on Boj3108.kt
> +    rectangles = Array(n) { br.readLine().split(" ").let { Rectangle(it) } }
제가 공부한 바로 부생성자에서도 주생성자를 한 번 호출해야하는 걸로 알고 있습니다. 
ex )
```
constructor(list: List<String>) : this(list[0].toInt(), ... 생략)
```
split()을 이 시그니쳐 옆 this()에 같이 사용할 방법이 생각이 안나서
backing property를 사용해 구현해보았습니다.

혹시 다른 좋은 방법이 있을까요?

backing property를 사용한 구현 )
```
class Rectangle(
    private var _x1: Int = 0,
    private var _y1: Int = 0,
    private var _x2: Int = 0,
    private var _y2: Int = 0,
) {
    val x1: Int
        get() = _x1

    val y1: Int
        get() = _y1

    val x2: Int
        get() = _x2

    val y2: Int
        get() = _y2

    constructor(inputStr: String) : this() {
        inputStr.split(' ').map { it.toInt() }.let { _x1 = it[0]; _y1 = it[1]; _x2 = it[2]; _y2 = it[3] }
    }
```

2023-10-10 06:46 UTC, Unagi-zoso commented on Boj10282.kt
> +    // backing property는 이렇게 쓰는건가요? 살짝 억지로 쓴 느낌이..
그렇군요! 감사합니다!

2023-10-10 06:46 UTC, Unagi-zoso commented on Boj10282.kt
> +import java.lang.Integer.max
네! 감사합니다!

2023-10-10 10:46 UTC, konempty commented on Boj12886.kt
> +data class Pair(val x: Int, val y: Int)
단순히 두개의 정보를 담는 Pair가 아닌 명시적으로 좌표평면의 한점을 나타내는 X,Y를 의미한다라는 의도는 정말 좋았는데
그렇다면 클래스 명을 Point라고 지었다면 더 좋았을것 같습니다 👍

2023-10-10 11:01 UTC, konempty commented on Boj3108.kt
> +    rectangles = Array(n) { br.readLine().split(" ").let { Rectangle(it) } }
```kotlin
data class Rectangle(
    val x1: Int = 0,
    val y1: Int = 0,
    val x2: Int = 0,
    val y2: Int = 0,
) {
    constructor(list: List<String>) : this(list[0].toInt(), list[1].toInt(), list[2].toInt(), list[3].toInt())
    constructor(str: String) : this(str.split(""))
}
```

알고리즘 문제 같이 작은 프로그램에서는 오버 엔지니어링이긴 하지만
부 생성자를 2개이상을 선언할수 있고 요렇게 체이닝으로 호출하도록 하는 패턴도 자주 사용합니다~!

2023-10-10 11:03 UTC, konempty commented on Boj12886.kt
> +    while (q.isNotEmpty()) { // 변수 재사용하기 싫어 의미없이 변수를 만드는 데 괜찮은건가 생각이 드네요.
네네 현재의 변수명은 가독성이 많이 떨어지지만 알고리즘 문제 풀이이기 때문에 눈감고 넘어갈수 있다고 생각해요 ㅋㅋㅋ...
하지만 l, r가 i,j역할을 수행하는건 한개의 변수가 여러개 역할을 가지는것 같아
역할 분리 측면에서 의문이 들긴하네요 ㅋㅋㅋ

2023-10-10 11:34 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
리뷰가 너무 길어지는것 같아서 요정도 리뷰만 일단 드리고
더 깊은내용은 추후에 더 어려운 내용 배우면 드리도록 하겠습니다~!

2023-10-10 11:34 UTC, konempty commented on Boj10282.kt
> +    val tempDependencyList = MutableList(100005) { ArrayList<ComparablePair<Int>>() }
ArrayList 대신 코틀린에서 지원하는 
MutableList 를 쓰는게 더 코틀린스러운 코드일것 같아요! ㅋㅋㅋ
아마 그냥 MutableList<ComparablePair<Int>>()가 안되서 요렇게 우회 하신것 같은데
코틀린에는 mutableListOf라는 팩토리 메소드를 지원합니다~!

따라서 아래와 같이 수정 가능합니다!

```kotlin
val tempDependencyList = MutableList(100005) { mutableListOf<Pair<Int, Int>>() }
```

2023-10-10 11:34 UTC, konempty commented on Boj12886.kt
> +    }
```kotlin
fun main() = System.out.bufferedWriter().use { writer ->
    System.`in`.bufferedReader().use { reader ->

        val (x, y, z) =
            reader.readLine().split(' ').map { it.toInt() }

        if ((x + y + z) % 3 == 0) writer.write("${bfs(x, y, z)}") else writer.write("0")
    }
}
```
요게 제가 의도했던코드입니다~!

2023-10-10 11:34 UTC, konempty commented on Boj2533.kt
> +    System.`in`.bufferedReader().use { reader ->
엇 ㅋㅋㅋ 여기는 잘 사용하셨네요

2023-10-10 11:34 UTC, konempty commented on Boj3108.kt
> +    }
```kotlin
data class Rectangle(
    val x1: Int = 0,
    val y1: Int = 0,
    val x2: Int = 0,
    val y2: Int = 0,
) {
    constructor(list: List<String>) : this(list[0].toInt(), list[1].toInt(), list[2].toInt(), list[3].toInt())
    constructor(str: String) : this(str.split(" "))
}
```
알고리즘 문제 같이 작은 프로그램에서는 오버 엔지니어링이긴 하지만
부 생성자를 2개이상을 선언할수 있고 요렇게 체이닝으로 호출하도록 하는 패턴도 자주 사용합니다~!

2023-10-10 11:34 UTC, konempty commented on Boj3108.kt
> +        repeat(n) { rectangles += Rectangle(reader.readLine()) } // readLine() 에서 'Possibly blocking call in non-blocking context could lead to thread starvation' warning이 뜨는데 어떤 왜 발생하는지 잘 모르겠습니다..
<img width="1083" alt="스크린샷 2023-10-10 오후 8 31 29" src="https://github.com/BI-kotlin-in-action/Juyeol-Song/assets/44064530/552bb060-8cf3-49b6-b7c7-99d353a53162">
엇 저한테는 안보이는걸 봐선 아마 일시적인 버그가 아닐까 싶네요 ㅋㅋㅋ
에러 메시지도 너무 뜬금없구요 ㅋㅋㅋㅋ

2023-10-10 12:01 UTC, Unagi-zoso commented on Boj12886.kt
> +data class Pair(val x: Int, val y: Int)
확실히 그게 좋아보이네요! 감사합니다!

2023-10-10 12:02 UTC, Unagi-zoso commented on Boj12886.kt
> +    while (q.isNotEmpty()) { // 변수 재사용하기 싫어 의미없이 변수를 만드는 데 괜찮은건가 생각이 드네요.
감사합니다!

2023-10-10 12:03 UTC, Unagi-zoso commented on Boj10282.kt
> +    val tempDependencyList = MutableList(100005) { ArrayList<ComparablePair<Int>>() }
참고하겠습니다! 감사합니다!

2023-10-10 12:04 UTC, Unagi-zoso commented on Boj12886.kt
> +    }
감사합니다!

2023-10-10 12:05 UTC, Unagi-zoso commented on Boj2533.kt
> +    System.`in`.bufferedReader().use { reader ->
어떤 형태가 더 좋다라는 판단이 안서서 여러 형태로 써봤어요. 감사합니다!

2023-10-10 12:06 UTC, Unagi-zoso commented on Boj3108.kt
> +    }
아 이렇게 하는 방법이 있었네요. 감사합니다!

2023-10-10 12:07 UTC, Unagi-zoso commented on Boj3108.kt
> +        repeat(n) { rectangles += Rectangle(reader.readLine()) } // readLine() 에서 'Possibly blocking call in non-blocking context could lead to thread starvation' warning이 뜨는데 어떤 왜 발생하는지 잘 모르겠습니다..
감사합니다!

2023-10-10 12:07 UTC, merged